spleeter:
  - name: "spleeter:2stems"
    description: "Performs vocals + accompaniment separation"
    supported_stems:
      - "vocals"
      - "accompaniment"
  - name: "spleeter:4stems"
    description: "Performs vocals + drums + bass + other separation"
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "spleeter:5stems"
    description: "Performs vocals + piano + drums + bass + other separation"
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "piano"
      - "other"

demucs:
  - name: "htdemucs_ft"
    description: "Fine-tuned version of htdemucs, separation will take 4 times more time but might be a bit better. Same training set as htdemucs"
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "htdemucs"
    description: "First version of Hybrid Transformer Demucs. Trained on MusDB + 800 songs. Default model."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "htdemucs_6s"
    description: "6 sources version of htdemucs, with piano and guitar being added as sources. Note that the piano source is not working great at the moment."
    supported_stems:
      - "vocals"
      - "piano"
      - "guitar"
      - "drums"
      - "bass"
      - "other"
  - name: "hdemucs_mmi"
    description: "Hybrid Demucs v3, retrained on MusDB + 800 songs."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "mdx"
    description: "Trained only on MusDB HQ, winning model on track A at the MDX challenge."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "mdx_extra"
    description: "Trained with extra training data (including MusDB test set), ranked 2nd on the track B of the MDX challenge."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "mdx_q"
    description: "Quantized version of mdx. Smaller download and storage but quality can be slightly worse."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
  - name: "mdx_extra_q"
    description: "Quantized version of mdx_extra. Smaller download and storage but quality can be slightly worse."
    supported_stems:
      - "vocals"
      - "drums"
      - "bass"
      - "other"
